name: Build wheels

on:
  repository_dispatch:
    types: Build wheels
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version for wheels
        shell: bash
        run: |
          export TAG=$(curl --silent https://api.github.com/repos/home-assistant/core/releases | jq -r 'map(select(.prerelease==false)) | first | .tag_name')
          export WHEELS_LIST=('PANDAS' 'NUMPY' 'PYNACL' 'CRYPTO' 'ORJSON' 'PILLOW')
          for wheel in "${WHEELS_LIST[@]}"; do export ${wheel}_VER=$(curl --silent https://raw.githubusercontent.com/home-assistant/core/$TAG/homeassistant/package_constraints.txt | grep -i "${wheel}=" | cut -d "=" -f3); done
          for wheel in "${WHEELS_LIST[@]}"; do echo "${wheel}_VER=$(${!wheel}_VER)" >> $GITHUB_ENV; done
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build and load the image
        run: |
          docker buildx build --load --tag wheels --build-arg PANDAS_VER=${{ env.PANDAS_VER }} --build-arg NUMPY_VER=${{ env.NUMPY_VER }} \
          --build-arg PYNACL_VER=${{ env.PYNACL_VER }} --build-arg CRYPTO_VER=${{ env.CRYPTO_VER }} --build-arg ORJSON_VER=${{ env.ORJSON_VER }} \
          --build-arg PILLOW_VER=${{ env.PILLOW_VER }} \
          --platform linux/arm/v5 --allow security.insecure --no-cache .
      - name: Copy wheels from the image
        shell: bash
        run: |
          docker create --name wheels wheels
          mkdir wheels
          docker cp wheels:./root/.cache/pip/wheels wheels
          
          export WHEELS_LIST=('PANDAS' 'NUMPY' 'PYNACL' 'CRYPTO' 'ORJSON' 'PILLOW')
          for wheel in "${WHEELS_LIST[@]}"; do export ${wheel}=$(find wheels/ -type f -name "*.whl" | grep -i "${wheel}")
          for wheel in "${WHEELS_LIST[@]}"; do echo "${wheel}=${wheel}" >> $GITHUB_ENV; done
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: |
            ${{ env.NUMPY }}
            ${{ env.PANDAS }}
            ${{ env.PYNACL }}
            ${{ env.CRYPTO }}
            ${{ env.ORJSON }}
            ${{ env.PILLOW }}
